<?php

namespace blaze\collections\queue;

/**
 * Test class for Stack.
 * Generated by PHPUnit on 2010-08-23 at 14:59:19.
 */
class StackTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Stack
     */
    protected $object;

    protected function setUp() {
        $this->object = new Stack();
        for($i = 0; $i<10;$i++){
            $this->object->push($i);
        }
    }

    protected function tearDown() {

    }

    public function testAdd() {
        // Remove the following lines when you implement this test.
        $this->assertTrue($this->object->add(11));

    }

    public function testAddAll() {
        // Remove the following lines when you implement this test.
        $list = new \blaze\collections\lists\ArrayList();
        $list->add(555);
        $list->add(558);
        $list->add(559);

        $this->assertTrue($this->object->addAll($list));
        $this->assertTrue($this->object->count() ==13);
      

    }

    public function testClear() {
        // Remove the following lines when you implement this test.
       $this->object->clear();
       $this->assertTrue($this->object->isEmpty());
    }

    public function testIsEmpty() {
        // Remove the following lines when you implement this test.
        $this->assertFalse($this->object->isEmpty());
        $this->object->clear();
        $this->assertFalse(!$this->object->isEmpty());

    }

    public function testGetIterator() {
        // Remove the following lines when you implement this test.
        $it = $this->object->getIterator();
        $this->assertTrue($it instanceof \Iterator);
        $i = 9;
        $test = false;
        foreach($this->object as $val){
            $this->assertTrue($val == $i);
            $i--;
            $test = true;
        }
        $this->assertTrue($test);
        $it->next();
        $this->assertTrue($it->current() === 8);
        $it->next();
        $it->next();
        $it->next();
        $it->remove();
        $this->assertTrue($this->object->search(5)==false);

    }

    public function testCount() {
        // Remove the following lines when you implement this test.
        $this->assertTrue($this->object->count()==10);
        $this->object->push(56);
        $this->assertTrue($this->object->count()==11);
        $this->object->remove(6);
        $this->assertTrue($this->object->count()==10);

    }

    public function testContains() {
        // Remove the following lines when you implement this test.
        $this->assertTrue($this->object->contains(4));
        $this->assertTrue($this->object->contains(1));
        $this->assertTrue($this->object->contains(8));
        $this->assertTrue(!$this->object->contains(855));
    }

    public function testContainsAll() {
        // Remove the following lines when you implement this test.
         $list = new \blaze\collections\lists\ArrayList();
        $list->add(5);
        $list->add(6);
        $list->add(7);
        $this->assertTrue($this->object->containsAll($list));
        $list->add(8798);
        $this->assertTrue(!$this->object->containsAll($list));
    }

    public function testRemove() {
        // Remove the following lines when you implement this test.
        $this->assertTrue($this->object->remove(2));
        $this->assertTrue($this->object->remove(4));
        $this->assertFalse($this->object->contains(2));

    }

    public function testRemoveAll() {
        // Remove the following lines when you implement this test.
        $list = new \blaze\collections\lists\ArrayList();
        $list->add(5);
        $list->add(6);
        $list->add(7);
        $this->assertTrue($this->object->removeAll($list));
        $this->assertFalse($this->object->contains(7));
        $this->assertFalse($this->object->contains(5));
        $this->assertFalse($this->object->contains(6));

        $list = new \blaze\collections\lists\ArrayList();
        $list->add(2);
        $list->add(89);
        $list->add(4);
        $this->assertTrue($this->object->removeAll($list));
        $this->assertFalse($this->object->contains(2));
        $this->assertFalse($this->object->contains(4));

        $list = new \blaze\collections\lists\ArrayList();
        $list->add(99);
        $list->add(89);
        $list->add(88);
        $this->assertFalse($this->object->removeAll($list));

    }

    public function testRetainAll() {
        // Remove the following lines when you implement this test.
        $list = new \blaze\collections\lists\ArrayList();
        $list->add(5);
        $list->add(6);
        $list->add(7);

        $this->assertTrue(($this->object->retainAll($list)));
        
    }

    public function testToArray() {
        // Remove the following lines when you implement this test.
        $this->assertTrue(\is_array($this->object->toArray()));

    }

    public function testPeek() {
        // Remove the following lines when you implement this test.
        $this->assertTrue($this->object->peek()==9);
        $this->assertTrue($this->object->peek()==9);
        $this->object->clear();
        $this->assertTrue($this->object->peek()==null);
    }

    public function testPoll() {
        // Remove the following lines when you implement this test.
         $this->assertTrue($this->object->poll()==9);
         $this->assertTrue($this->object->poll()==8);

        $this->object->clear();
        $this->assertTrue($this->object->poll()==null);
    }

    public function testPop() {
        // Remove the following lines when you implement this test.
         $this->assertTrue($this->object->pop()==9);
         $this->assertTrue($this->object->pop()==8);
         $this->assertTrue($this->object->pop()==7);
    }

    public function testPush() {
        // Remove the following lines when you implement this test.
        $this->object->push(99);
        $this->assertTrue($this->object->pop()==99);
        $this->assertTrue($this->object->pop()!=99);
    }

    public function testSearch() {
        // Remove the following lines when you implement this test.
        $this->assertTrue($this->object->search(5)==6);
        $this->assertTrue(!$this->object->search(555));
    }

    public function testALL(){
        $this->assertTrue($this->object->count() == 10);
        $this->assertTrue($this->object->pop() == 9);
        $this->assertTrue($this->object->count() == 9);
        $this->object->push(1);
        $this->assertTrue($this->object->remove(1));
        $this->object->push(78);
        
    }

}

?>
