<?php
namespace blaze\lang;

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../src/blaze/lang/Object.php';
require_once dirname(__FILE__).'/../../../src/blaze/lang/ClassLoader.php';
spl_autoload_register('blaze\lang\ClassLoader::autoLoad');

/**
 * Test class for Object.
 * Generated by PHPUnit on 2010-06-17 at 22:30:17.
 */
class DataSourceManagerTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var Object
     */
    protected $dsm;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->dsm = \blaze\ds\DataSourceManager::getInstance();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }


    /**
     * 
     */
    public function testDataSourceManager() {
        $ds = $this->dsm->getDataSource('bdsc:pdomysql://localhost/mydb?uid=root');
        $con = $ds->getConnection();
        $this->assertNotNull($con);
        $this->assertFalse($con->isClosed());
    }
}
?>
