<?php
namespace blazeServer;

/**
 * Test class for Object.
 * Generated by PHPUnit on 2010-04-12 at 22:30:17.
 */
class ObjectTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var array[blazeServer\Main]
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = array();
        for($i = 0; $i < 100; $i++)
            $this->object[$i] = new Main;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    

    /**
     * @todo Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        
    }

    /**
     * @todo Implement testGetClass().
     */
    public function testPerformance() {
        // Remove the following lines when you implement this test.
        foreach($this->object as $obj)
                $obj->run();
    }

}
?>
