<?php

namespace blaze\persistence;

/**
 * Test class for PersistenceConfigurationTest.
 * Generated by PHPUnit on 2010-08-31 at 23:54:33.
 */
class QueryBuilderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var blaze\persistence\EntityManagerFactory
     */
    protected $fact;


    protected function setUp() {
        $conf = new cfg\Configuration();
        $conf->configureFile('D:\\xampp\\htdocs\\BlazeFrameworkServer\\src\\blazeCMS\\source\\persistence.cfg.xml');
        $this->fact = $conf->buildEntityManagerFactory();
    }

    protected function tearDown() {

    }

    public function testQuery(){
        $sess = $this->fact->openEntityManager();
        $qb = QueryBuilder::createFromBuilder();
        $qb->fromEntity('User', 'u')->where('u.userId', '1', ooql\Condition::COND_EQUALS);
        $stmt = $qb->getStatement();
        $query = $sess->createQuery($stmt);
        $list = $query->getList();
    }
}

?>
