<?php
namespace blaze\lang;

/**
 * Test class for Object.
 * Generated by PHPUnit on 2010-04-12 at 22:30:17.
 */
class ObjectTest extends \PHPUnit_Framework_TestCase {
    /**
     * @var Object
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Object;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testCloneObject().
     */
    public function testCloneObject() {
        // Remove the following lines when you implement this test.
        $this->assertEquals($this->object, $this->object->cloneObject());
    }

    /**
     * @todo Implement testEquals().
     */
    public function testEquals() {
        // Remove the following lines when you implement this test.
        $this->assertTrue($this->object->equals($this->object->cloneObject()));
    }

    /**
     * @todo Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        
    }

    /**
     * @todo Implement testGetClass().
     */
    public function testGetClass() {
        // Remove the following lines when you implement this test.
        $class = $this->object->getClass();
        $this->assertNotNull($class);
        $this->assertEquals('blaze\lang\Object', $class->getName());
        $this->assertEquals('blaze\lang\Object', ClassWrapper::forName('blaze\lang\Object')->getName());
    }

    /**
     * @todo Implement testHashCode().
     */
    public function testHashCode() {
        // Remove the following lines when you implement this test.
        $this->assertNotNull($this->object->hashCode());
    }

    /**
     * @todo Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->assertRegExp('/blaze\\\\lang\\\\Object@[A-F0-9]*/', $this->object->__toString()->toNative());
    }
}
?>
