<?php

namespace blaze\io;

require_once 'D:/xampp/htdocs/BlazeFrameworkServer/src/blaze/lang/Reflectable.php';
require_once 'D:/xampp/htdocs/BlazeFrameworkServer/src/blaze/lang/Object.php';
require_once 'D:/xampp/htdocs/BlazeFrameworkServer/src/blaze/lang/ClassLoader.php';
spl_autoload_register('blaze\lang\ClassLoader::autoLoad');

/**
 * Test class for Serialization.
 * Generated by PHPUnit on 2010-08-19 at 03:27:44.
 */
class SerializationTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ObjectOutputStream
     */
    protected $out;
    /**
     * @var ObjectInputStream
     */
    protected $in;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $pos = new \blaze\io\output\PipedOutputStream();
        $pis = new \blaze\io\input\PipedInputStream($pos);
        $this->out = new \blaze\io\output\ObjectOutputStream($pos);
        $this->in = new \blaze\io\input\ObjectInputStream($pis);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testWrite().
     */
    public function testWrite() {

    }

    /**
     * @todo Implement testWriteBoolean().
     */
    public function testWriteBoolean() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testWriteInt().
     */
    public function testWriteInt() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testWriteFloat().
     */
    public function testWriteFloat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testWriteLong().
     */
    public function testWriteLong() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testWriteDouble().
     */
    public function testWriteDouble() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testWriteShort().
     */
    public function testWriteShort() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testWriteByte().
     */
    public function testWriteByte() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testWriteObject().
     */
    public function testWriteObject() {
        $this->out->writeObject(new \blaze\lang\String('It works'));
        $a = $this->in->readObject();
        $this->assertTrue($a instanceof \blaze\lang\String);
    }

    /**
     * @todo Implement testWriteObjectOverride().
     */
    public function testWriteObjectOverride() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDefaultWriteObject().
     */
    public function testDefaultWriteObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testFlush().
     */
    public function testFlush() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testClose().
     */
    public function testClose() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testIsClosed().
     */
    public function testIsClosed() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
