<?php

namespace blaze\math;

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../src/blaze/math/BigDecimal.php';

/**
 * Test class for BigDecimal.
 * Generated by PHPUnit on 2010-07-21 at 09:30:56.
 */
class BigDecimalTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var BigDecimal
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new BigDecimal('87458644845312845',2,1,null);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        echo($this->object);
    }

}
?>
