<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../../src/blaze/lang/Object.php';
require_once dirname(__FILE__).'/../../../src/blaze/lang/ClassLoader.php';
require_once dirname(__FILE__) . '/../../../src/blaze/math/BigInteger.php';

/**
 * Test class for BigInteger.
 * Generated by PHPUnit on 2010-07-20 at 09:42:34.
 */
class BigIntegerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var BigInteger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new BigInteger('45894984848949845486');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testCompareTo().
     */
    public function testCompareTo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement test__toString().
     */
    public function test__toString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
?>
